[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-lobby"
version = "3.17.0"
description = "AccelByte Python SDK - Justice Lobby Server"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

