[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-basic"
version = "2.8.0"
description = "AccelByte Python SDK - Justice Basic Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

