[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-matchmaking"
version = "2.22.0"
description = "AccelByte Python SDK - Justice Matchmaking Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

