[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-iam"
version = "5.31.0"
description = "AccelByte Python SDK - Justice IAM Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

