[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-service-gametelemetry"
version = "1.19.0"
description = "AccelByte Python SDK - Analytics Game Telemetry"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]