[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-qosm"
version = "1.18.0"
description = "AccelByte Python SDK - Justice QoS Manager Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

