[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-eventlog"
version = "2.0.0"
description = "AccelByte Python SDK - Justice Event Log Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

