[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-reporting"
version = "0.1.25"
description = "AccelByte Python SDK - Justice Reporting Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

