[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-sessionbrowser"
version = "1.13.4"
description = "AccelByte Python SDK - Justice Session Browser Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

