[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-achievement"
version = "2.17.0"
description = "AccelByte Python SDK - Justice Achievement Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

