[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-platform"
version = "4.27.0"
description = "AccelByte Python SDK - Justice Platform Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

