[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-social"
version = "2.3.0"
description = "AccelByte Python SDK - Justice Social Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

