[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-group"
version = "2.15.3"
description = "AccelByte Python SDK - Justice Group Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

