[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-legal"
version = "1.28.1"
description = "AccelByte Python SDK - Justice Legal Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

