[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-seasonpass"
version = "1.18.2"
description = "AccelByte Python SDK - Justice SeasonPass Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

