[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-ams"
version = "0.2.1"
description = "AccelByte Python SDK - Manage AMS Fleets"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

