[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-cloudsave"
version = "3.6.4"
description = "AccelByte Python SDK - Justice Cloudsave Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

