[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "accelbyte-py-sdk-leaderboard"
version = "2.19.5"
description = "AccelByte Python SDK - Justice Leaderboard Service"
requires-python = ">=3.9"
dependencies = [
    "accelbyte-py-sdk-core",
]

